/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RailwayTickets;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import RailwayTickets.PurchaseTicket;




/**
 *
 * @author Mohin
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }
    public void close(){
      WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
     Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
     
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lUsername = new javax.swing.JLabel();
        jtxtUserName = new javax.swing.JTextField();
        lPassword = new javax.swing.JLabel();
        jtxtPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mHome = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bangladesh Railway");
        setBackground(new java.awt.Color(102, 255, 102));
        getContentPane().setLayout(null);

        lUsername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lUsername.setForeground(new java.awt.Color(153, 255, 255));
        lUsername.setText("User Name");
        getContentPane().add(lUsername);
        lUsername.setBounds(338, 251, 100, 17);
        getContentPane().add(jtxtUserName);
        jtxtUserName.setBounds(454, 248, 124, 20);

        lPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lPassword.setForeground(new java.awt.Color(153, 255, 255));
        lPassword.setText("Password");
        getContentPane().add(lPassword);
        lPassword.setBounds(342, 292, 70, 17);
        getContentPane().add(jtxtPassword);
        jtxtPassword.setBounds(454, 292, 124, 20);

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(384, 356, 73, 23);

        jButton2.setBackground(new java.awt.Color(153, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(484, 356, 53, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 255));
        jLabel1.setText("           Admin Login");
        jLabel1.setAlignmentY(0.0F);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(358, 182, 230, 48);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RailwayTickets/download.png"))); // NOI18N
        jLabel3.setText("Banglasesh Railway Ticketing System");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(54, 11, 646, 68);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RailwayTickets/admin.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(68, 182, 191, 167);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mohin\\Desktop\\daily_sun_BR_coaches_picture.jpg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 0, 790, 390);

        jMenuBar1.setBackground(new java.awt.Color(102, 255, 102));

        mHome.setText("Home");
        jMenuBar1.add(mHome);

        jMenu2.setText("Purchase Ticket");

        jMenuItem1.setText("Login");
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       System.exit(0);
     
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         // close();
      // PurchaseTicket pt=new PurchaseTicket();
     //  pt.setVisible(true);
       String username=jtxtUserName.getText();
        String password=jtxtPassword.getText();
        if(username.contains("mohsin") &&(password.contains("52247"))){
             JOptionPane.showMessageDialog(null,"welcome","Login Success",JOptionPane.PLAIN_MESSAGE);
        jtxtUserName.setText(null);
        jtxtPassword.setText(null);
          close();
       PurchaseTicket pt=new PurchaseTicket();
       pt.setVisible(true);
        }
        else{
        JOptionPane.showMessageDialog(null,"Invalid Login Details","Login Eroor",JOptionPane.ERROR_MESSAGE);
        
        jtxtUserName.setText(null);
        jtxtPassword.setText(null);
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPasswordField jtxtPassword;
    private javax.swing.JTextField jtxtUserName;
    private javax.swing.JLabel lPassword;
    private javax.swing.JLabel lUsername;
    private javax.swing.JMenu mHome;
    // End of variables declaration//GEN-END:variables
}





